name: Build scpca-tools image

on:
  push:
    branches:
      - main
      - jashapiro/vireo-image

env:
  REGISTRY: ghcr.io
  VIREO_IMAGE: alexslemonade/vireo-snp

jobs:
  build_push_vireo:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.VIREO_IMAGE }}
          tags: |
            type=semver,pattern={{raw}}

      - uses: docker/build-push-action@v3
        with:
          context: images/vireo-snp
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

